branches:
  except:
    - gh-pages
language: node_js
node_js:
  - "8"
before_script:
  - npm install
before_install:
- openssl aes-256-cbc -K $encrypted_eb7b9e2e2d7d_key -iv $encrypted_eb7b9e2e2d7d_iv
  -in id_rsa.enc -out id_rsa -d
